# python异常

## 什么是异常？

    当检测到一个错误时，Python解释器就无法继续执行了，反而出现了一些错误的提示，这就是所谓的“异常”，也就是我们常说的BUG

## bug单词的诞生

    早期计算机采用大量继电器工作，马克二型计算机就是这样的。

    1945年9月9日，下午三点，马克二型计算机无法正常工作了，技术人员试了很多办法，最后定位到第70号继电器出错。负责人哈珀观察这个出错的继电器，发现一只飞蛾躺在中间，已经被继电器打死。她小心地用摄子将蛾子夹出来，用透明胶布站到 “事件记录本” 中，并注明“第一个发现虫子的实例。〞自此之后，引发软件失效的缺陷，便被称为Bug。

## 为什么需要捕获异常

当我们的程序遇到了BUG，那么接下来有两种情况：

1. 整个程序因为一个BUG停止运行
2. 对BUG进行提醒，整个程序继续运行

显然在之前的学习中，我们所有的程序**遇到BUG**就会出现 **1的这种情况**，也就是整个程序直接奔溃

但是在真实工作中，我们肯定不能因为一个小的BUG就让整个程序全部奔溃，也就是我们希望的是达到**2的这种情况**

那这里我们就需要使用到 **捕获异常**

**捕获异常的作用在于：提前假设某处会出现异常，做好提前准备，当真的出现异常的时候，可以有后续手段。**

## 捕获常规异常

1. 基本语法：

        try:
        可能发生错误的代码
        except:
        如果出现异常执行的代码

2. 快速入门：

    需求：尝试以'r'模式打开文件，如果文件不存在，则以'w'方式打开。

        try:
            f= open('linux.txt', 'r')
        except:
            f = open('linux.txt', 'w')

        try:
            print(name)
        except NameError as e:
            print('name变量名称未定义错误")

3. 捕获多个异常:

    当捕获多个异常时，可以把要捕获的异常类型的名字，放到except 后，并使用元组的方式进行书写。

        try:
            print(1/0)
        except (NameError, ZeroDivisionError):
            print('ZeroDivision错误...")

4. 捕获所有异常

    try:
        1 / 0
    except Exception as e:
        print("出现异常了")

5. 异常else

    else表示的是如果没有异常要执行的代码。

        try:
            print(1)
        except Exception as e:
            print(e)
        else:
            print('我是else，是没有异常的时候执行的代码')

6. 异常的finally

    finally表示的是无论是否异常都要执行的代码，例如关闭文件。

    try:
        f = open('test.txt', 'r')
    except Exception as e:
        f = open('test.txt', 'w')
    else:
        print('没有异常，真开心')
    finally:
        f.close()

## 异常的传递

异常是具有传递性的

当函数**func01**中发生异常，并且没有捕获处理这个异常的时候，异常会传递到**函数func02**，当func02也没有捕获处理这个异常的时候**main函数**会捕获这个异常，这就是**异常的传递性**。

>提示：当所有函数都没有捕获异常的时候，程序就会报错

    def func01(): # 异常在funcor中没有被捕获
        print（"这是func01开始"）
        num = 1 / 0
        print("这是func01结束")

    def func02 (): # 异常在funco2中没有被捕获
        print（"这是func02开始"）
        func01()
        print("这是func02结束")

    def main(): # 异常在mian中被捕获
        try:
            func02()
        except Exception as e:
            print(e)

